#!/usr/bin/env bash
# Disable window picker
gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize'
# Maintain window picker
#gsettings set org.gnome.shell.extensions.dash-to-dock click-action 'minimize-or-previews'
